apiVersion: v1
kind: Service
metadata:
  labels:
    app: websvc
  name: websvc
spec:
  ports:
  - name: "web-port"
    nodePort: 32000
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    dept: smartapp
  type: NodePort
